Add conditions to exit if repositories cannot be found

diff --git a/github_migrator b/github_migrator
--- a/github_migrator
+++ b/github_migrator
@@ -7,9 +7,9 @@
 # v0.2
 
 set -e
-ORGANIZATION="bashworks"
-GITHUB_ACCESS_TOKEN="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"
-GITHUB_USERNAME="fayad"
+ORGANIZATION=""
+GITHUB_ACCESS_TOKEN=""
+GITHUB_USERNAME=""
 
 backup_status() 
 {
@@ -21,17 +21,15 @@ backup_status()
 }
 
 if [ "$1" = "--backup" ] || [ "$1" = "backup" ] && [ -n "$ORGANIZATION" ] && [ -n "$GITHUB_ACCESS_TOKEN" ] && [ -n "$GITHUB_USERNAME" ] ; then
-			echo "Initiating backup for all repositories in $ORGANIZATION, you can run github_migrator --status to check backup status. Please do not run --backup more than once to avoid duplicates."
+			echo "Initiating backup for all repositories in $ORGANIZATION, you can run github_migrator --status to check backup status. Avoid running --backup more than once to avoid duplicates."
 			for repo in `curl -s -H "Authorization: token $GITHUB_ACCESS_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/$ORGANIZATION/repos | grep '"full_name"' | awk '{print $2}' | cut -d'/' -f2 | cut -d'"' -f1`; do
-			# if [ -n "$repo" ]; then 
-			# 	echo "Backup could not be initiated. Please try again after checking dependencies." 
-			# 	exit 3
-			# else
+			if [ -z $repo ]; then 
+				echo "Backup could not be initiated. Please try again after checking dependencies." 
+				exit 3
+			else
 				curl -s -H "Authorization: token $GITHUB_ACCESS_TOKEN" -X POST -H "Accept: application/vnd.github.wyandotte-preview+json" -d'{"lock_repositories":false,"repositories":["'$ORGANIZATION'/'$repo'"]}' https://api.github.com/orgs/$ORGANIZATION/migrations -o /dev/null  && echo "Backup initiated for $repo." || echo "Backup for $repo cannot be initiated."
-				# exit 3
-			# fi
+			fi
 			done
-			backup_status
 	elif [ "$1" = "--download" ] || [ "$1" = "download" ] && [ -n "$ORGANIZATION" ] && [ -n "$GITHUB_ACCESS_TOKEN" ] && [ -n "$GITHUB_USERNAME" ]; then
 	 		backup_status > /dev/null
 			for url in `grep exported ./migration-status | awk '{print $3}'`; do
@@ -48,9 +46,9 @@ if [ "$1" = "--backup" ] || [ "$1" = "backup" ] && [ -n "$ORGANIZATION" ] && [ -
 	echo "Instructions"
 	echo "------------"
 	echo "Requires curl command."
-	echo "Before proceeding, edit this script and add Organization, Access Token (as owner) and Username. And run"
-	echo "github_migrator {backup, download,status}"
-	echo "For eg. github_migrator --status"
+	echo "Before proceeding, edit this script and add Organization, Access Token (as owner) and Username."
+	echo "Usage: ./github_migrator {backup, download,status}"
+	echo "Eg. ./github_migrator --status"
 	echo "Do not run --backup more than once - to avoid duplicates."
 	else echo "Please run with one of the arguments and by adding Organization, Access Token (as owner) and Username. Check --help for details."
 fi
